### ISSUE TITLE
Parser data from yahoo finance query was failed

### ISSUE THREAD

**Issue by givenchyhuang** [Lili-Updating/projects#1]
### Hi ,

I could not run data_acquisition.py to parser the data from the yahoo finance page.
------  setting.py content --------- 
QUERY_START_DATE = '2016-07-01'
QUERY_END_DATE = '2016-07-31'

---

------- error message --------
Table cannot be found in the link https://finance.yahoo.com/q/hp?s=%5EGSPC&a=6&b=1&c=2016&d=6&e=31&f=2016&g=d. This may be caused by network problem. Try later.
Traceback (most recent call last):
  File "./data_acquisition.py", line 115, in <module>
    main()
  File "./data_acquisition.py", line 107, in main
    aggregate_data_to_mysql(total_table, first_link, output_table, database_connection)
  File "./data_acquisition.py", line 60, in aggregate_data_to_mysql
    table_head, page_table, new_page = scrape_page_data(pageUrl)
  File "./data_acquisition.py", line 42, in scrape_page_data
    table_heads = table.select('th')
UnboundLocalError: local variable 'table' referenced before assignment

---

However the code is still workable ?
I have modify a cvs file[date , Open , High, Close , Volume, Adj Close] to match the code.
But I found  << pd.rolling_mean(df['Close'], window=5).shift(1)  and the same as other pd.rolling_mean >> cause NaN value, then fail to do the calculation  .
---- message ----
2016-07-01         NaN
2016-07-05         NaN
2016-07-06         NaN
2016-07-07         NaN
2016-07-08         NaN
2016-07-11    2103.806
2016-07-12    2110.648
...
mae_regression = sum(abs(df_prediction['Actual'] - df_prediction['Predicted_regression'])) / len(df_prediction['Predicted_regression'])
ZeroDivisionError: integer division or modulo by zero

---

os : mac 
python -v : 2.7
pandas 0.17

Thank you for your help : DDDD

**Comment by Lili-Updating** [comment]
-- Yahoo Finance website has changed, especially the table on the webpage. I just took a loot at the page source code and found the html code was different. That's why my code doesn't work any more. One shortage of web scraping code is that it is specific to html code. Once the webpage changes, its html code changes, which will cause the failure of web scraping code. That's because html tags and elements are used in the web scraping code. 

I will update the code once I get time to do it.

-- 'NaN' values have to been dropped first before analysis. If you take a look at prediction.py, you will find the statement df = df.dropna(axis=0), which is to drop NaN values. 

Feel free to let me know if there is anything I can help further.

**Comment by givenchyhuang** [comment]
Ok , I understood the question about web.
It doesn't matter : DDDD

Attached file was training file - train.csv (2016-07-01 to 2016-07-31) and testing file (2016-08-01 to 2016-08-11).
I modified the window size to 1 , 5 , 10 (original 5 , 30 365) because my dataset was too small.
But I followed the process and found [ ratio_avg_close_price_5_365 ,std_close_price_day_5,std_close_price_day_5] these variables value was NaN.

------ error message -------
Traceback (most recent call last):
  File "./prediction.py", line 142, in <module>
    main()
  File "./prediction.py", line 136, in main
    df_prediction = predict(df, prediction_start_date, prediction_end_date, predict_tommorrow)
  File "./prediction.py", line 104, in predict
    mae_regression = sum(abs(df_prediction['Actual'] - df_prediction['Predicted_regression'])) / len(df_prediction['Predicted_regression'])
ZeroDivisionError: integer division or modulo by zero

---

Should I get more data to training or other problem of my modification ?? :((

**Comment by Lili-Updating** [comment]
Let me first clarify how the rolling statistics are calculated. Let's take 'avg_close_price_day_5' for example. In this project, the 'avg_close_price_day_5' value for 2016-07-01 is the rolling mean of 'close price' of the past 5 days, which is from 2016-06-26 to 2016-06-30. If the 'close price' values are not available for some of those days, then 'avg_close_price_day_5' value for 2016-07-01 will be marked as 'NaN'.

The maximum window size is 10, after you modified them. That means that 'avg_close_price_day_10' value for the first 10 rows, which is from 2016-07-01 to 2016-07-10, are 'NaN's.

**All 'NaN' values must be dropped, before you apply the prediction model on those data.** Note that in prediction.py, the statement df = df.dropna(axis=0) is behind all data calculation including rolling statistics and right before the model.

If you just want to play with the code, I guess you can add several more months data. If you want to get more accurate prediction and add all available historical data, feel free to refer to [this post](http://lovelearning9.blogspot.com/2015/12/the-first-python-project-in-data.html). More explanation about this project can be found there. 

Feel free to let me know if there is anything I can help further. :)

**Comment by givenchyhuang** [comment]
Hi 

I just added the 2016-06-01 to 2016-06-31 data in train.csv as attached file. 
[Archive 2.zip](https://github.com/Lili-Updating/projects/files/416854/Archive.2.zip)

I could see the NaN value in [avg_close_price_day_5 , avg_close_price_day_30, avg_close_price_day_365] in these variables.  

But it still got the same NaN value about [ratio_avg_close_price_5_365 ,std_close_price_day_5,std_close_price_day_5] ] all date which was from 0601 to 0731.
====== here are error message =====
Traceback (most recent call last):
  File "./prediction.py", line 143, in <module>
    main()
  File "./prediction.py", line 137, in main
    df_prediction = predict(df, prediction_start_date, prediction_end_date, predict_tommorrow)
  File "./prediction.py", line 105, in predict
    mae_regression = sum(abs(df_prediction['Actual'] - df_prediction['Predicted_regression'])) / len(df_prediction['Predicted_regression'])
ZeroDivisionError: integer division or modulo by zero

# 

Could you please just run the code with my input and tell the wrong step with me : ((((

**Comment by Lili-Updating** [comment]
-- It doesn't make sense to calculate of standard deviation of only 1 element. You changed the window size 5 in my code to the window size 1. Accordingly, when you calculate 'std_close_price_day_5', you are actually calculating the standard deviation of close price in the past 1 day and you will get NaN for that. 

Change the window size 1 to 2 or more. 

-- It turns out that almost the first one month's data need to be dropped. In my last reply, I mentioned that the first 10 rows needed to be dropped, because of NaN values in 'avg_close_price_365'. But 'ratio_avg_close_price_5_365' is calculated based on 'avg_close_price_365'. So the second 10 rows need to be dropped because of that, plus weekend dates (the stock market is closed on weekends). 

Add a few more months' data. 

I quickly developed a program based on your needs. It is in the folder 'new_version'. See https://github.com/Lili-Updating/projects/commit/96a132a9a08165852a5cdea88d237501fe8c9834

In that program, the window size is 2, 5, 10, although I don't think it makes sense in practice. But I understand that you just want to play with the code. The train data is from 2016-05-01 to 2016-07-31, but technically it is  2016-06-01 to 2016-07-31, because data in 2016-05-xx will be dropped because of NaNs. The test data is from 2016-08-01 to 2016-08-11. 

I guess this program is simple for you to play with. You may want to download it now, because I am going to prototype it and replace it later.

**Comment by Lili-Updating** [comment]
The code that is specific to your needs can be found in the commit history. See https://github.com/Lili-Updating/projects/commit/96a132a9a08165852a5cdea88d237501fe8c9834

**Comment by givenchyhuang** [comment]
It is very helpful !!!!
I found my original setting.py and cvs file which was setting wrong.
I compared the original file to your new version and I need to set the PREDICTION_START_DATE to cvs first date which was not predicted day.
And I need to add data 2016-08-01 ~ 2016-08-11 to train.csv

I will trace your code and post to understood your method !!!

Thanks for your time : (((

**Comment by Lili-Updating** [comment]
Glad that it is helpful.

Because there is no code script in the archive you attached, I don't know the exact changes you have made in the code. 

I will try to make the notes/comments/explanations about my code more clear. 

Feel free to let me know if there is anything I can help further. :)

**Comment by givenchyhuang** [comment]
closes #1
